### ISSUE TITLE
Stock API calculates NaN with y points of same value

### ISSUE THREAD

**Issue by inuwan** [andreaferretti/paths-js#21]
The Stock API calculates NaN for the line.centroid[1]

I pass in the following to pathsjs.Stock({
data: [
  {
    "date": new Date("2015-01-09T07:00:00.000Z"),
    "netPay": 200.45
  },
  {
    "date": new Date("2015-01-23T07:00:00.000Z"),
    "netPay": 200.45
  },
  {
    "date": new Date("2015-02-06T07:00:00.000Z"),
    "netPay": 200.45
  },
  {
    "date": new Date("2015-02-20T07:00:00.000Z"),
    "netPay": 200.45
  },
  {
    "date": new Date("2015-03-06T07:00:00.000Z"),
    "netPay": 200.45
  }
],
xaccessor: function(x) {return x.date.valueOf();},
yaccessor: function(x){x.netPay;),
width: 414,
height: 80
})

The resulting paths.curves[0].line.centroid[0] is 207 and paths.curves[0].line.centroid[0] is NaN

**Comment by andreaferretti** [comment]
I have published version 0.3.4, where this should be fixed. What I was doing was rescale the y range over the screen coordinates range, which does not make much sense when the y range is reduced to a single point, as in your example. I have now added a slight padding when all y values are the same. I'm not sure this will be enough to handle degenerate cases, please comment here to let me know if you have any more problems, so that I can also expand my test suite.

**Comment by andreaferretti** [comment]
It seems to be fixed, so I am closing this. Please, reopen it if needed
