### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by jonathanmv** [andreaferretti/paths-js#22]
When i try to use the dist/global/paths.js i get *Uncaught ReferenceError: path is not defined*. 
You can see a simple demo going to https://jsfiddle.net/aqmh3eax/ and opening developer tools.

It uses a script that is loaded using [rawgit](http://rawgit.com/). More info about [linkning raw github files from jsfiddle](http://geekdave.com/2013/06/19/linking-raw-github-files-from-jsfiddle/)

**Comment by andreaferretti** [comment]
It seems I have messed up something in the build passing from 0.3.2 to 0.3.3. In fact, [linking an older version](https://jsfiddle.net/La1h0s5o/1/) seems to work.

I am very sorry for the inconvenience, I will fix it now

**Comment by andreaferretti** [comment]
Ok, I have fixed it - it was a change in the AMDClean API which I had missed. Since this only affects the global (single file) build, I am not sure whether it makes sense to publish a new version. The version downloaded from the repository now works fine. I think it would affect only people who use Bower to get the file and then use the global script instead of AMD.

Please, comment here if you want a new version to be published
