### ISSUE TITLE
Graph Layout

### ISSUE THREAD

**Issue by omidb** [andreaferretti/paths-js#24]
Hi,

thanks for the awesome lib, I'm using scala version path.js. I was wondering if there is a way to put graph layout algorithms into path.js highlevel api. something like dager.js or so. I would appreciate your idea about the best way to this using path-scala-js.

thanks

**Comment by andreaferretti** [comment]
Hi, I am not familiar with `dager.js`. I only found [this NPM project](https://www.npmjs.com/package/dager) but it is not clear from the documentation whether it can do layout.

About graph layout algorithms: I would be very happy to [accept contributions](https://github.com/andreaferretti/paths-js/wiki/Contributing). In fact, the major pain point right now is the slowness of the current graph layout algorithm. It would be very nice to replace it, or - if the new algorithm has a different API - to add a new chart altogether. I could not find the time to go back and improve the algorithm, but if you have something in mind, every contribution (even at the level of idea) would be appreciated!

About paths-scala-js: right now, it is just a wrapper over the js library. The obvious reason is that paths.js predated scala.js, but even if not, adding the price of the scala.js runtime (even if stripped out by the Closure compiler) may not be acceptable for people using paths.js from javascript. Currently, paths.js is written in coffeescript, which compiles rather directly to js without any runtime or standard library, and is essentially just a more convenient syntax for js.

After the feature is fleshed out in coffee, wrapping it in scala.js is a rather simple and mechanical procedure.

If you feel like contributing, but you want to avoid writing js or coffee, I may try to do a translation from scala.js. But in general graph layout algorithms are heavy for the GC, hence it is hard to write them in a functional style, so that the advantage of using scala.js may be not great in this case

**Comment by omidb** [comment]
Hi,

my bad, I misspelled it. it's [dagre-d3](https://github.com/cpettitt/dagre-d3) and [dagre-js](https://github.com/cpettitt/dagre).
it's really fast and nice layouting JS code.

**Comment by andreaferretti** [comment]
`dagre` seems nice - especially the list of recommended reading is a good starting point (altough I recommend [this](http://cs.brown.edu/%7Ert/gdhandbook/chapters/force-directed.pdf) as well).

Are you interested in wrapping dagre or porting the algorithms? I have intentionally avoided any third party dependencies in paths-js, because managing transitive dependencies in a way that is compatible with both AMD and CommonJS is a nightmare (if possible at all). But it would be very nice to exploit some of those ideas to improve the current layout.

**Comment by omidb** [comment]
I'm not a good JS/coffee programmer. I was trying to port dagre to scala.js but in middle of the process, I thought it's better to have all of these functionality as path-js high-level library. Most of the visualizations algorithm has a d3 implementation and I have no idea what is the best way to combine all these and react and .... SO confused right now

**Comment by andreaferretti** [comment]
Well, paths.js tries to be an alternative to d3, while staying much smaller in scope by avoiding the whole rendering part, as well as the numerous utilities that are present in d3.

In fact, the reason I started writing paths.js is exactly that I had troubles integrating d3 with various frontend frameworks (Backbone at the time, but the same would be true for React, Angular, Mithril and so on). The reason is that d3 is based on the concept of iterating on data and explicitly modifying the DOM, while those frameworks think they have full control over the page. It is not impossible to make them work peacefully with d3, but usually it is a bit of a hassle.

So I wanted something that would compute just the layout of various charts based on data, and then I would render that myself, using whatever templating/data binding features the framework offered. This would also allow to get something more declarative and hence easier to inspect and modify.

One could in theory use d3 to do various layout computations, but since this is just one of many parts of d3, I thought that a specialized library would make more sense, and this is why I started doing paths. In short: I think that combining paths.js and d3 is not a really good idea. :-)

* paths.js + d3 -> you don't want to do this
* d3 + react -> requires some work, not a good match
* paths.js + react -> designed exactly for this

Now, of course d3 still has a big edge in terms of how many layout algorithms are available, as well as online examples. I would love to expand paths.js to cover more cases and add many more examples to the demos, but at the moment I am not really working on the frontend and I do not have much time to improve it (but of course I still fix bugs and so on).

**Comment by omidb** [comment]
thanks, I think [dagre.js](https://github.com/cpettitt/dagre) also focus just on layouting so it should be easy to add it in path-js highlevel algorithm with one interface. If you could find anytime to write the interface in coffee-script, it would be great. If not, I will use directly in my scala code.
Thanks for your awesome lib and also for porting it in scala.js ;)

**Comment by andreaferretti** [comment]
Writing an interface to dagre would not be difficult. What would be difficult is having paths.js depend on dagre, while still making sure that people can import paths both as an AMD or a CommonJS module or a global script.

It may seem crazy, but in the js world there is no standard way as of today of managing dependencies and this essentially makes it impossible to have a library depend on another library in a transparent way (that is, without requiring client code to take care of the dependency as well).

This is why I have a strict policy of not depending on external libraries for paths. I would still be interested in a clean-slate implementation though! ;-)
