### ISSUE TITLE
Latest builds are broken

### ISSUE THREAD

**Issue by dfunckt** [andreaferretti/paths-js#26]
`dist/global/paths.js` is broken for the last couple of releases (at least until 0.3.3 -- didn't check earlier). [Latest commit](https://github.com/andreaferretti/paths-js/commit/e0aed09eca06d826273c2fa42cc273d64997bb28) fixes the issue but there's been no release incorporating it so far. It'd be wonderful if you released a new version with the fix.

**Comment by andreaferretti** [comment]
Uh? There is 0.3.4 exactly for this reason. Both packages.json and bower.json show version 0.3.4, and there is a git tag as well.

I am pretty sure that global should work, because it is the version I am using with [Scala.js](https://github.com/andreaferretti/paths-scala-js), via [Webjars](http://www.webjars.org/).

What is not working for you?

**Comment by dfunckt** [comment]
Yeah, but the issue exists in 0.3.4. This is [dist/global/paths.js@0.3.4](https://github.com/andreaferretti/paths-js/blob/0.3.4/dist/global/paths.js), and it doesn't work -- you will have to scroll to the very end of the file to see that it references undefined vars.

**Comment by andreaferretti** [comment]
Ok, I will check and in case publish 0.3.5

**Comment by andreaferretti** [comment]
You were right, I published 0.3.5

**Comment by andreaferretti** [comment]
I have also updated `paths-scala-js` to make use of 0.3.5, and at the same time took the opportunity to make some compatibility fixes for scala-js 0.6.5
