### ISSUE TITLE
[Questions] polyfill and SVG generate path

### ISSUE THREAD

**Issue by thednp** [andreaferretti/paths-js#28]
I have two question:
* What polyfills are required for this script to run? Would my [minifill](https://github.com/thednp/minifill) cover the needs for paths.js?
* Does this script generate path for given SVG elements that don't have it? Like below?

```html
<path d="M 100 100 L 300 100 L 200 300 z" fill="red" stroke="blue" stroke-width="3" />
```

Thanks so much.

**Comment by andreaferretti** [comment]
Paths.js is a pure javascript library (no interaction with the DOM or other API), hence does not need a lot in terms of polyfills. The only relatively recent thing that Paths.js needs is support for some Array methods from ES5. You can use [this polyfill](https://github.com/kriskowal/es5-shim/) on browsers that only support ES3.

On the other hand, Paths.js does not draw anything to the screen - its only task is generating the string that you put in the `d` attribute of a path (in your example `"M 100 100 L 300 100 L 200 300 z"`). You will need to use Paths.js together with a templating library in order to render to the screen, such as Mustache, or else a more complete framework such as React, Angular and so on. Each of them has its own requirements in terms of browser support.

Finally, you will probably need a browser capable of rendering SVG elements. For older browsers, this will probably be the biggest issue. You could use a third party library to that renders SVG to a canvas, such as [this one](https://github.com/gabelerner/canvg), but the problem is that older browsers, such as IE8, do not support canvas either.

I am not sure what you are asking in your second question, could you be more clear?

**Comment by thednp** [comment]
Hi, sorry I forgot about this.

My questions should have sounded like this: if I want to morph a SVG from a path to another (their path string would be quite different as we may expect), can this script help getting the two paths "processed" and ready for `requestAnimationFrame` tweening?

**Comment by andreaferretti** [comment]
It depends. If you already have two paths on the screen, then no, this is not what you are looking for.

If instead you use the library to generate the path strings inside some render loop, then yes. For instance, the logo on the [demo](http://andreaferretti.github.io/paths-js-react-demo/) is clickable. When you click it, I morph the logo path and get it back to the original one.

I do this by [animating the state](https://github.com/andreaferretti/paths-js-react-demo/blob/master/js/components/logo.jsx) in a React component and rendering a path that depends on the state.

The animation of the state itself is done by a simple interpolation + tweening, which I do in [this helper mixin](https://github.com/andreaferretti/paths-js-react-demo/blob/master/js/animate.jsx#L138-L158). Here you see that I use requestAnimationFrame during the interpolation.

**Comment by thednp** [comment]
Thank you for the time to explain.

**Comment by andreaferretti** [comment]
In short, the library is a collection of functions (data + geometric information) => path string.

If this is what you need, great! It will not help you in either going the other way (parsing) or rendering to the screen (I assume you use some framework for this)

**Comment by thednp** [comment]
I use tween.js and my own kute.js (a fork of tween.js) for animations, and I'm researching anything about morphing SVG to create a morphSVG plugin for my kute.js.

**Comment by andreaferretti** [comment]
Then you should be good to go. You can use kute to interpolate parameters,
and then paths to generate svg strings for these parameters

Il giovedì 3 dicembre 2015, thednp <notifications@github.com> ha scritto:
